{
 "title": "Plant",
 "time": { "from": "1969-12-31T23:59:59.453Z", "to": "1970-01-01T00:00:07.964Z" },
 "panels": [
  {
   "title": "RAW_DATA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CV",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"First\"\nFROM operational_layer.oscilloscope_data\nwhere feature='cv' and filename='1.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Second\"\nFROM operational_layer.oscilloscope_data\nwhere feature='cv' and filename='2.xml'\norder by x asc"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Third\"\nFROM operational_layer.oscilloscope_data\nwhere feature='cv' and filename='3.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Forth\"\nFROM operational_layer.oscilloscope_data\nwhere feature='cv' and filename='4.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Fifth\"\nFROM operational_layer.oscilloscope_data\nwhere feature='cv' and filename='5.xml'\norder by x asc\n\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y_mean as \"EXPECTED VALUE\"\nFROM operational_layer.oscilloscope_data\nwhere feature='cv' and filename='5.xml'\norder by x asc\n\n"
      }
     ]
    },
    {
     "title": "VFV",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"First\"\nFROM operational_layer.oscilloscope_data\nwhere feature='vfv' and filename='1.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Second\"\nFROM operational_layer.oscilloscope_data\nwhere feature='vfv' and filename='2.xml'\norder by x asc"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Third\"\nFROM operational_layer.oscilloscope_data\nwhere feature='vfv' and filename='3.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Forth\"\nFROM operational_layer.oscilloscope_data\nwhere feature='vfv' and filename='4.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Fifth\"\nFROM operational_layer.oscilloscope_data\nwhere feature='vfv' and filename='5.xml'\norder by x asc\n\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y_mean as \"EXPECTED VALUE\"\nFROM operational_layer.oscilloscope_data\nwhere feature='vfv' and filename='5.xml'\norder by x asc\n\n"
      }
     ]
    },
    {
     "title": "PFV",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"First\"\nFROM operational_layer.oscilloscope_data\nwhere feature='pfv' and filename='1.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Second\"\nFROM operational_layer.oscilloscope_data\nwhere feature='pfv' and filename='2.xml'\norder by x asc"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Third\"\nFROM operational_layer.oscilloscope_data\nwhere feature='pfv' and filename='3.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Forth\"\nFROM operational_layer.oscilloscope_data\nwhere feature='pfv' and filename='4.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Fifth\"\nFROM operational_layer.oscilloscope_data\nwhere feature='pfv' and filename='5.xml'\norder by x asc\n\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y_mean as \"EXPECTED VALUE\"\nFROM operational_layer.oscilloscope_data\nwhere feature='pfv' and filename='5.xml'\norder by x asc\n\n"
      }
     ]
    },
    {
     "title": "PCV",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"First\"\nFROM operational_layer.oscilloscope_data\nwhere feature='pcv' and filename='1.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Second\"\nFROM operational_layer.oscilloscope_data\nwhere feature='pcv' and filename='2.xml'\norder by x asc"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Third\"\nFROM operational_layer.oscilloscope_data\nwhere feature='pcv' and filename='3.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Forth\"\nFROM operational_layer.oscilloscope_data\nwhere feature='pcv' and filename='4.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Fifth\"\nFROM operational_layer.oscilloscope_data\nwhere feature='pcv' and filename='5.xml'\norder by x asc\n\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y_mean as \"EXPECTED VALUE\"\nFROM operational_layer.oscilloscope_data\nwhere feature='pcv' and filename='5.xml'\norder by x asc\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Anomaly_score",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CV",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"First\"\nFROM operational_layer.oscilloscope_data\nwhere feature='cv' and filename='1.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Second\"\nFROM operational_layer.oscilloscope_data\nwhere feature='cv' and filename='2.xml'\norder by x asc"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Third\"\nFROM operational_layer.oscilloscope_data\nwhere feature='cv' and filename='3.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Forth\"\nFROM operational_layer.oscilloscope_data\nwhere feature='cv' and filename='4.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Fifth\"\nFROM operational_layer.oscilloscope_data\nwhere feature='cv' and filename='5.xml'\norder by x asc\n\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y_mean as \"EXPECTED VALUE\"\nFROM operational_layer.oscilloscope_data\nwhere feature='cv' and filename='5.xml'\norder by x asc\n\n"
      }
     ]
    },
    {
     "title": "VFV",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"First\"\nFROM operational_layer.oscilloscope_data\nwhere feature='vfv' and filename='1.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Second\"\nFROM operational_layer.oscilloscope_data\nwhere feature='vfv' and filename='2.xml'\norder by x asc"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Third\"\nFROM operational_layer.oscilloscope_data\nwhere feature='vfv' and filename='3.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Forth\"\nFROM operational_layer.oscilloscope_data\nwhere feature='vfv' and filename='4.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y as \"Fifth\"\nFROM operational_layer.oscilloscope_data\nwhere feature='vfv' and filename='5.xml'\norder by x asc\n\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  y_mean as \"EXPECTED VALUE\"\nFROM operational_layer.oscilloscope_data\nwhere feature='vfv' and filename='5.xml'\norder by x asc\n\n"
      }
     ]
    },
    {
     "title": "CV_Anomaly_detection",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  deviation as \"First\"\nFROM operational_layer.oscilloscope_data\nwhere feature='cv' and filename='1.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  deviation as \"Second\"\nFROM operational_layer.oscilloscope_data\nwhere feature='cv' and filename='2.xml'\norder by x asc"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  deviation as \"Third\"\nFROM operational_layer.oscilloscope_data\nwhere feature='cv' and filename='3.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  deviation as \"Forth\"\nFROM operational_layer.oscilloscope_data\nwhere feature='cv' and filename='4.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  deviation as \"Fifth\"\nFROM operational_layer.oscilloscope_data\nwhere feature='cv' and filename='5.xml'\norder by x asc\n\n"
      }
     ]
    },
    {
     "title": "VFV_Anomaly_detection",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  deviation as \"First\"\nFROM operational_layer.oscilloscope_data\nwhere feature='vfv' and filename='1.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  deviation as \"Second\"\nFROM operational_layer.oscilloscope_data\nwhere feature='vfv' and filename='2.xml'\norder by x asc"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  deviation as \"Third\"\nFROM operational_layer.oscilloscope_data\nwhere feature='vfv' and filename='3.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  deviation as \"Forth\"\nFROM operational_layer.oscilloscope_data\nwhere feature='vfv' and filename='4.xml'\norder by x asc\n"
      },
      {
       "rawSql": "SELECT\n  x::numeric AS \"time\",\n  deviation as \"Fifth\"\nFROM operational_layer.oscilloscope_data\nwhere feature='vfv' and filename='5.xml'\norder by x asc\n\n"
      }
     ]
    }
   ]
  }
 ]
}